### ISSUE TITLE
Create a logo for the project

### ISSUE THREAD

**Issue by Benardi** [Benardi/touvlo#12]
The logo should be created around the idea of bricks/building blocks.

**Comment by 0xHericles** [comment]
Taken

**Comment by palakjadwani** [comment]
Can I also take this?

**Comment by parikshitgupta1** [comment]
### **which logo?** ![bitmoji](https://render.bitstrips.com/v2/cpanel/9d438724-a1e5-44b9-9172-377503bbffe6-6f97b0bd-04bb-4ab7-ba76-db69e1517e0e-v1.png?transparent=1&palette=1&width=246)
