### ISSUE TITLE
Build package whilst exposing submodules

### ISSUE THREAD

**Issue by Benardi** [Benardi/touvlo#32]
#### Description
Add logic to touvlo to package it whilst  maintaining its submodules

For instance being able to do the following:
```
from touvlo.supv import lin_rg
from touvlo.unsupv import kmeans
from touvlo.utils import gradient_descent

```

#### Files
* `touvlo/__init__.py`
* `setup.py`
* `setup.cfg`

#### Tasks
- [ ] Update/configure **touvlo** to allow one to build/install it as a package that allows one to access its submodules

**Comment by rafaelcascalho** [comment]
Hey! I'm working on this one and would like to know if there's an interest in publishing it in `PyPI`, cause, in that case, I'd be necessary to add an `author` to the setup.

**Comment by Benardi** [comment]
> Hey! I'm working on this one and would like to know if there's an interest in publishing it in `PyPI`, cause, in that case, I'd be necessary to add an `author` to the setup.

Yes, there is.
