### ISSUE TITLE
Create sub-modules and their respective sub-pages in the documentation

### ISSUE THREAD

**Issue by Benardi** [Benardi/touvlo#9]
1. Group the existing modules in the submodules  `supv` and `unsupv`, as follows:
* module `supv`:
        + `lin_rg`
        + `lgx_rg`
        + `nn`
* module `unsupv` :
       + `kmeans`

2. Configure the docs' restructuredtext files to create a subpage for `supv` and `unsupv`. 
* The documentation of  `supv`'s members should be at `supv` subpage.
* The documentation of  `unsupv`'s members should be at `unsupv` subpage.

**Comment by yuriy-os** [comment]
Mind if I help you with this issue too?

**Comment by Benardi** [comment]
I would appreciate the help
